// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: akmHL7cLduyNG7qpZ1XTQy
// Component: ovWPjnzJPPx6

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: aIriiZFUvLZH/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../untitled_project/plasmic_untitled_project.module.css"; // plasmic-import: akmHL7cLduyNG7qpZ1XTQy/projectcss
import sty from "./PlasmicJhgj.module.css"; // plasmic-import: ovWPjnzJPPx6/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: GtGXW4o3_oX3/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: NZoV8-eLSy-q/icon

createPlasmicElementProxy;

export type PlasmicJhgj__VariantMembers = {};
export type PlasmicJhgj__VariantsArgs = {};
type VariantPropType = keyof PlasmicJhgj__VariantsArgs;
export const PlasmicJhgj__VariantProps = new Array<VariantPropType>();

export type PlasmicJhgj__ArgsType = {};
type ArgPropType = keyof PlasmicJhgj__ArgsType;
export const PlasmicJhgj__ArgProps = new Array<ArgPropType>();

export type PlasmicJhgj__OverridesType = {
  root?: Flex__<"div">;
  button?: Flex__<typeof Button>;
};

export interface DefaultJhgjProps {
  className?: string;
}

const $$ = {};

function PlasmicJhgj__RenderFunc(props: {
  variants: PlasmicJhgj__VariantsArgs;
  args: PlasmicJhgj__ArgsType;
  overrides: PlasmicJhgj__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        className={classNames("__wab_instance", sty.button)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicJhgj__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicJhgj__VariantsArgs;
    args?: PlasmicJhgj__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicJhgj__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicJhgj__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicJhgj__ArgProps,
          internalVariantPropNames: PlasmicJhgj__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicJhgj__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicJhgj";
  } else {
    func.displayName = `PlasmicJhgj.${nodeName}`;
  }
  return func;
}

export const PlasmicJhgj = Object.assign(
  // Top-level PlasmicJhgj renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicJhgj
    internalVariantProps: PlasmicJhgj__VariantProps,
    internalArgProps: PlasmicJhgj__ArgProps
  }
);

export default PlasmicJhgj;
/* prettier-ignore-end */
